### ISSUE TITLE
Pull requests not getting merged despite corresponding SR being accepted into Factory for weeks

### ISSUE THREAD

**Issue by badshah400** [aplanas/openSUSE-git#42]
See pending PRs: <https://src.opensuse.org/pool/CastXML/pulls/1>, <https://src.opensuse.org/pool/armadillo/pulls/2>.

Apparently I do not have permissions to merge PRs on src.o.o even for packages I am a designated maintainer for in the OBS devel project.

It seems no one else does either, and the CastXML PR,, for instance, has remained open for a week or so after the corresponding SR was checked into Factory. This means the develprj package has not been synced with Factory either and an over-zealous automatic obs-submit bot just submitted a [new SR](https://build.opensuse.org/request/show/1187485) from the develprj to Factory that would have accidentally downgraded the package back but for sensible human Factory maintainers who declined the request.

**Comment by AdamMajer** [comment]
FWIW, these PR should not be merged there by hand. If they are not auto-merged, it's a bug.

CastXML looks like managed in git, per package data, so the branch, at very least, should be merged to factory status.

**Comment by badshah400** [comment]
I see. Anyway, to whoever merged these two PRs today, big thanks. If the auto-merge bug has been fixed, thanks for that too.

I'll leave the issue open for a dev to determine if it should be closed instead.

**Comment by AdamMajer** [comment]
I'll close it. Probably the bot crashed and needed prodding :smile:
