### ISSUE TITLE
Import from openSUSE:Factory incomplete

### ISSUE THREAD

**Issue by jengelh** [aplanas/openSUSE-git#43]
https://src.opensuse.org/pool/jmol exists, but https://src.opensuse.org/pool/gfan & https://src.opensuse.org/pool/gf2x do not, even though all three have long been packages in openSUSE:Factory. Is this a known issue?
cc @dirkmueller

**Comment by AdamMajer** [comment]
The repositories exist, but nothing is pushed into them. We'll have to deal with this when we import `science` devel project to git.

**Comment by dirkmueller** [comment]
these two: qfan and qf2x now exist and pool will be populated automatically now.
